src/main/java/org/primefaces/cookbook/controller/chapter6/BaseMenuBean.java
package org.primefaces.cookbook.controller.chapter6;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;
import java.io.Serializable;

/**
 * BaseMenuBean
 *
 * @author  Oleg Varaksin / last modified by $Author: $
 * @version $Revision: 1.0 $
 */
public abstract class BaseMenuBean implements Serializable {

	public void save(ActionEvent ae) {
		FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "Saved", null);
		FacesContext.getCurrentInstance().addMessage(null, msg);
	}

	public void update(ActionEvent ae) {
		FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "Updated", null);
		FacesContext.getCurrentInstance().addMessage(null, msg);
	}

	public void delete(ActionEvent ae) {
		FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "Deleted", null);
		FacesContext.getCurrentInstance().addMessage(null, msg);
	}

	public String doSomething() {
		// do something
		FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "Done", null);
		FacesContext.getCurrentInstance().addMessage(null, msg);

		return null;
	}
}

src/main/java/org/primefaces/cookbook/controller/chapter6/CheckboxMenuBean.java
package org.primefaces.cookbook.controller.chapter6;

import javax.faces.model.SelectItem;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/**
 * CheckboxMenuBean
 *
 * @author  Oleg Varaksin / last modified by $Author: $
 * @version $Revision: 1.0 $
 */
@Named
@ViewScoped
public class CheckboxMenuBean implements Serializable {

	private List<SelectItem> languages;
	private Map<String, String> color;
	private List<Locale> selectedLanguages;
	private List<String> selectedColors;

	public List<SelectItem> getLanguages() {
		if (languages == null) {
			languages = new ArrayList<SelectItem>();
			languages.add(new SelectItem(new Locale("de"), "German"));
			languages.add(new SelectItem(new Locale("en"), "English"));
			languages.add(new SelectItem(new Locale("it"), "Italian"));
			languages.add(new SelectItem(new Locale("fr"), "French"));
		}

		return languages;
	}

	public Map<String, String> getColors() {
		if (color == null) {
			color = new HashMap<String, String>();
			color.put("Red", "Red");
			color.put("Green", "Green");
			color.put("Blue", "Blue");
			color.put("Orange", "Orange");
		}

		return color;
	}

	public List<Locale> getSelectedLanguages() {
		return selectedLanguages;
	}

	public void setSelectedLanguages(List<Locale> selectedLanguages) {
		this.selectedLanguages = selectedLanguages;
	}

	public List<String> getSelectedColors() {
		return selectedColors;
	}

	public void setSelectedColors(List<String> selectedColors) {
		this.selectedColors = selectedColors;
	}
}

src/main/java/org/primefaces/cookbook/controller/chapter6/ContextMenuBean.java
package org.primefaces.cookbook.controller.chapter6;

import org.primefaces.event.NodeSelectEvent;
import org.primefaces.event.NodeUnselectEvent;
import org.primefaces.model.DefaultTreeNode;
import org.primefaces.model.TreeNode;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Named;

/**
 * ContextMenuBean
 *
 * @author  Oleg Varaksin / last modified by $Author: $
 * @version $Revision: 1.0 $
 */
@Named
@ViewScoped
public class ContextMenuBean extends BaseMenuBean {

    private TreeNode root;
    private TreeNode selectedNode;

    @PostConstruct
    protected void initialize() {
        root = new DefaultTreeNode("Root", null);

        TreeNode node0 = new DefaultTreeNode("Folder 0", root);
        TreeNode node1 = new DefaultTreeNode("Folder 1", root);
        TreeNode node2 = new DefaultTreeNode("Folder 2", root);
        TreeNode node00 = new DefaultTreeNode("Folder 0.0", node0);
        TreeNode node01 = new DefaultTreeNode("Folder 0.1", node0);
        TreeNode node10 = new DefaultTreeNode("Folder 1.0", node1);
        new DefaultTreeNode("File 1.1", node1);
        new DefaultTreeNode("File 2.0", node2);
        new DefaultTreeNode("File 0.0.0", node00);
        new DefaultTreeNode("File 0.0.1", node00);
        new DefaultTreeNode("File 0.1.0", node01);
        new DefaultTreeNode("File 1.0.0", node10);
    }

    public TreeNode getRoot() {
        return root;
    }

    public TreeNode getSelectedNode() {
        return selectedNode;
    }

    public void setSelectedNode(TreeNode selectedNode) {
        this.selectedNode = selectedNode;
    }

    public void onNodeSelect(NodeSelectEvent event) {
        selectedNode = event.getTreeNode();
    }

    public void onNodeUnselect(NodeUnselectEvent event) {
        selectedNode = null;
    }

    public void viewNode() {
        if (selectedNode == null) {
            return;
        }

        FacesMessage msg = new FacesMessage(
            FacesMessage.SEVERITY_INFO,
            "Selected", selectedNode.getData().toString());
        FacesContext.getCurrentInstance().addMessage(null, msg);
    }

    public void deleteNode() {
        if (selectedNode == null) {
            return;
        }

        selectedNode.getChildren().clear();
        selectedNode.getParent().getChildren().remove(selectedNode);
        selectedNode.setParent(null);

        selectedNode = null;
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter6/MegaMenuBean.java
package org.primefaces.cookbook.controller.chapter6;

import javax.faces.view.ViewScoped;
import javax.inject.Named;
import java.io.Serializable;

/**
 * MegaMenuBean
 *
 * @author  Oleg Varaksin / last modified by $Author: $
 * @version $Revision: 1.0 $
 */
@Named
@ViewScoped
public class MegaMenuBean implements Serializable {

	public String getItems() {
		return "Bought items: ...";
	}
}

src/main/java/org/primefaces/cookbook/controller/chapter6/MenuButtonBean.java
package org.primefaces.cookbook.controller.chapter6;

import javax.faces.view.ViewScoped;
import javax.inject.Named;

/**
 * MenuButtonBean
 *
 * @author  Oleg Varaksin / last modified by $Author: $
 * @version $Revision: 1.0 $
 */
@Named
@ViewScoped
public class MenuButtonBean extends BaseMenuBean {
}

src/main/java/org/primefaces/cookbook/controller/chapter6/MenubarBean.java
package org.primefaces.cookbook.controller.chapter6;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import java.io.Serializable;

/**
 * MenubarBean
 *
 * @author  Oleg Varaksin / last modified by $Author: $
 * @version $Revision: 1.0 $
 */
@Named
@ViewScoped
public class MenubarBean implements Serializable {

	public void createFolder(ActionEvent ae) {
		FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "Create Folder", null);
		FacesContext.getCurrentInstance().addMessage(null, msg);
	}

	public void createVideo(ActionEvent ae) {
		FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "Create Video File", null);
		FacesContext.getCurrentInstance().addMessage(null, msg);
	}

	public void createHTML(ActionEvent ae) {
		FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "Create HTML File", null);
		FacesContext.getCurrentInstance().addMessage(null, msg);
	}

	public void properties(ActionEvent ae) {
		FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "Properties", null);
		FacesContext.getCurrentInstance().addMessage(null, msg);
	}

	public void cut(ActionEvent ae) {
		FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "Cut", null);
		FacesContext.getCurrentInstance().addMessage(null, msg);
	}

	public void copy(ActionEvent ae) {
		FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "Copy", null);
		FacesContext.getCurrentInstance().addMessage(null, msg);
	}

	public void paste(ActionEvent ae) {
		FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "Paste", null);
		FacesContext.getCurrentInstance().addMessage(null, msg);
	}

	public void zoomIn(ActionEvent ae) {
		FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "Zoom In", null);
		FacesContext.getCurrentInstance().addMessage(null, msg);
	}

	public void zoomOut(ActionEvent ae) {
		FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "Zoom Out", null);
		FacesContext.getCurrentInstance().addMessage(null, msg);
	}

	public void viewIcons(ActionEvent ae) {
		FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "View Icons", null);
		FacesContext.getCurrentInstance().addMessage(null, msg);
	}

	public void viewCompact(ActionEvent ae) {
		FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "View Compact", null);
		FacesContext.getCurrentInstance().addMessage(null, msg);
	}

	public void viewDetails(ActionEvent ae) {
		FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "View Details", null);
		FacesContext.getCurrentInstance().addMessage(null, msg);
	}

	public String info() {
		FacesContext.getCurrentInstance().getExternalContext().getFlash().put("helpVisible", true);

		return "/views/chapter6/menubar.xhtml";
	}
}

src/main/java/org/primefaces/cookbook/controller/chapter6/PanelMenuBean.java
package org.primefaces.cookbook.controller.chapter6;

import javax.faces.view.ViewScoped;
import javax.inject.Named;

/**
 * PanelMenuBean
 *
 * @author  Oleg Varaksin / last modified by $Author: $
 * @version $Revision: 1.0 $
 */
@Named
@ViewScoped
public class PanelMenuBean extends BaseMenuBean {
}

src/main/java/org/primefaces/cookbook/controller/chapter6/ParametrizedCommandBean.java
package org.primefaces.cookbook.controller.chapter6;

import org.primefaces.event.MenuActionEvent;
import org.primefaces.model.menu.DefaultMenuItem;
import org.primefaces.model.menu.DefaultMenuModel;
import org.primefaces.model.menu.MenuModel;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import java.io.Serializable;
import java.util.List;
import java.util.Map;

/**
 * ProgrammaticMenuParamsBean
 *
 * @author Oleg Varaksin / last modified by $Author: $
 * @version $Revision: 1.0 $
 */
@Named
@ViewScoped
public class ParametrizedCommandBean implements Serializable {

    private MenuModel model;

    @PostConstruct
    protected void initialize() {
        model = new DefaultMenuModel();
    
        DefaultMenuItem item = new DefaultMenuItem();
        item.setValue("Command with parameters");
        item.setCommand("#{parametrizedCommandBean.command}");
        item.setUpdate("growl");
        item.setIcon("ui-icon-play");
        item.setParam("book", "PrimeFaces Cookbook");
        item.setParam("edition", "Second Edition");
    
        model.addElement(item);
    }
    
    public void command(MenuActionEvent event) {
        DefaultMenuItem item = (DefaultMenuItem) event.getMenuItem();
        Map<String, List<String>> params = item.getParams();
    
        FacesMessage msg = new FacesMessage(
            FacesMessage.SEVERITY_INFO,
            params.get("book").get(0) + ", " + 
            params.get("edition").get(0), null);
        FacesContext.getCurrentInstance().addMessage(null, msg);
    }

    public MenuModel getModel() {
        return model;
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter6/PositionedMenuBean.java
package org.primefaces.cookbook.controller.chapter6;

import javax.faces.view.ViewScoped;
import javax.inject.Named;

/**
 * PositionedMenuBean
 *
 * @author  Oleg Varaksin / last modified by $Author: $
 * @version $Revision: 1.0 $
 */
@Named
@ViewScoped
public class PositionedMenuBean extends BaseMenuBean {
}

src/main/java/org/primefaces/cookbook/controller/chapter6/ProgrammaticMenuBean.java
package org.primefaces.cookbook.controller.chapter6;

import org.primefaces.model.menu.DefaultMenuItem;
import org.primefaces.model.menu.DefaultMenuModel;
import org.primefaces.model.menu.DefaultSubMenu;
import org.primefaces.model.menu.MenuModel;

import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import java.io.Serializable;


/**
 * ProgrammaticMenuBean
 *
 * @author  Oleg Varaksin / last modified by $Author: $
 * @version $Revision: 1.0 $
 */
@Named
@ViewScoped
public class ProgrammaticMenuBean implements Serializable {

    private MenuModel model;

    @PostConstruct
    protected void initialize() {
        model = new DefaultMenuModel();

        // first submenu
        DefaultSubMenu submenu = new DefaultSubMenu();
        submenu.setLabel("JavaScript Libraries");

        // menu items
        DefaultMenuItem item = new DefaultMenuItem();
        item.setValue("jQuery");
        item.setUrl("http://jquery.com");
        submenu.addElement(item);

        item = new DefaultMenuItem();
        item.setValue("Yahoo UI");
        item.setUrl("http://yuilibrary.com");
        submenu.addElement(item);

        item = new DefaultMenuItem();
        item.setValue("Prototype");
        item.setUrl("http://prototypejs.org");
        submenu.addElement(item);

        model.addElement(submenu);

        // second submenu
        submenu = new DefaultSubMenu();
        submenu.setLabel("Operations");

        // menu items
        item = new DefaultMenuItem();
        item.setValue("Save");
        item.setCommand("#{positionedMenuBean.save}");
        item.setUpdate("growl");
        submenu.addElement(item);

        item = new DefaultMenuItem();
        item.setValue("Update");
        item.setCommand("#{positionedMenuBean.update}");
        item.setUpdate("growl");
        submenu.addElement(item);

        item = new DefaultMenuItem();
        item.setValue("Delete");
        item.setCommand("#{positionedMenuBean.delete}");
        item.setUpdate("growl");
        submenu.addElement(item);

        model.addElement(submenu);
    }

    public MenuModel getModel() {
        return model;
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter6/SlideMenuBean.java
package org.primefaces.cookbook.controller.chapter6;

import javax.faces.view.ViewScoped;
import javax.inject.Named;

/**
 * SlideMenuBean
 *
 * @author  Oleg Varaksin / last modified by $Author: $
 * @version $Revision: 1.0 $
 */
@Named
@ViewScoped
public class SlideMenuBean extends BaseMenuBean {
}

src/main/java/org/primefaces/cookbook/controller/chapter6/TieredMenuBean.java
package org.primefaces.cookbook.controller.chapter6;

import javax.faces.view.ViewScoped;
import javax.inject.Named;

/**
 * TieredMenuBean
 *
 * @author  Oleg Varaksin / last modified by $Author: $
 * @version $Revision: 1.0 $
 */
@Named
@ViewScoped
public class TieredMenuBean extends BaseMenuBean {
}

src/main/webapp/views/chapter6/breadcrumb.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">
        
        <p:growl id="growl"/>
        
        <h3 style="margin-top:0">Breadcrumb with icon for the root link</h3>

        <p:breadCrumb>
            <p:menuitem value="PrimeFaces" url="http://primefaces.org"/>
            <p:menuitem value="jQuery" url="http://jquery.com"/>
            <p:menuitem value="Yahoo UI" url="http://yuilibrary.com"/>
            <p:menuitem value="Save"
                        actionListener="#{positionedMenuBean.save}"
                        update="growl"/>
            <p:menuitem value="Update"
                        actionListener="#{positionedMenuBean.update}"
                        update="growl"/>
        </p:breadCrumb>
        
        <h3 style="margin-top:20px">Breadcrumb with text for the root link</h3>
        
        <p:breadCrumb homeDisplay="text">
            <p:menuitem value="PrimeFaces" url="http://primefaces.org"/>
            <p:menuitem value="jQuery" url="http://jquery.com"/>
            <p:menuitem value="Yahoo UI" url="http://yuilibrary.com"/>
            <p:menuitem value="Save"
                        actionListener="#{positionedMenuBean.save}"
                        update="growl"/>
            <p:menuitem value="Update"
                        actionListener="#{positionedMenuBean.update}"
                        update="growl"/>
        </p:breadCrumb>

    </ui:define>
</ui:composition>

src/main/webapp/views/chapter6/checkboxMenu.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://primefaces.org/ui" xmlns:h="http://xmlns.jcp.org/jsf/html"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">

        <h3 style="margin-top:0">Simple SelectCheckboxMenu</h3>

        <p:selectCheckboxMenu label="Colors"
                              value="#{checkboxMenuBean.selectedColors}">
            <f:selectItems value="#{checkboxMenuBean.colors}"/>
        </p:selectCheckboxMenu>

        <h3 style="margin-top:20px">
            Advanced SelectCheckboxMenu with filter and converter
        </h3>

        <p:selectCheckboxMenu label="Languages" filter="true"
                              value="#{checkboxMenuBean.selectedLanguages}">
            <f:selectItems value="#{checkboxMenuBean.languages}"/>
            <f:converter
                    converterId="org.primefaces.cookbook.converter.LocaleConverter"/>
        </p:selectCheckboxMenu>

        <p:commandButton value="Submit" update="display"
                         oncomplete="PF('dlg').show()"
                         style="margin-top:20px; display:block;"/>

        <p:dialog header="Selected colors and languages" widgetVar="dlg">
            <h:panelGroup id="display">
                <p:dataList value="#{checkboxMenuBean.selectedColors}" var="color">
                    #{color}
                </p:dataList>
                <p:dataList value="#{checkboxMenuBean.selectedLanguages}" var="lang">
                    #{lang}
                </p:dataList>
            </h:panelGroup>
        </p:dialog>

    </ui:define>
</ui:composition>

src/main/webapp/views/chapter6/contextMenu.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">

        <p:growl id="growl"/>

        <p:panel id="dummyPanel" header="Please click somewhere on panel to see a context menu">
            <h:panelGroup layout="block" style="height:100px;"/>
        </p:panel>

        <p:contextMenu for="dummyPanel">
            <p:submenu label="JavaScript Libraries">
                <p:menuitem value="jQuery" url="http://jquery.com"/>
                <p:menuitem value="Yahoo UI" url="http://yuilibrary.com"/>
                <p:menuitem value="Prototype" url="http://prototypejs.org"/>
            </p:submenu>
            <p:separator/>
            <p:submenu label="Operations">
                <p:menuitem value="Save"
                            actionListener="#{contextMenuBean.save}"
                            update="growl"/>
                <p:menuitem value="Update"
                            actionListener="#{contextMenuBean.update}"
                            update="growl"/>
                <p:menuitem value="Delete"
                            actionListener="#{contextMenuBean.delete}"
                            update="growl"/>
            </p:submenu>
        </p:contextMenu>

    </ui:define>
</ui:composition>

src/main/webapp/views/chapter6/contextMenuIntegration.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">

        <p:growl id="growl" showDetail="true"/>

        <p:contextMenu for="fileSystem">
            <p:menuitem value="View" update="growl"
                        actionListener="#{contextMenuBean.viewNode}"
                        icon="ui-icon-search"/>
            <p:menuitem value="Delete" update="fileSystem"
                        actionListener="#{contextMenuBean.deleteNode}"
                        icon="ui-icon-close"/>
        </p:contextMenu>

        <p:tree id="fileSystem" value="#{contextMenuBean.root}"
                var="node" dynamic="true"
                cache="false" selectionMode="single"
                selection="#{contextMenuBean.selectedNode}">
            <p:ajax event="select" listener="#{contextMenuBean.onNodeSelect}"/>
            <p:ajax event="unselect" listener="#{contextMenuBean.onNodeUnselect}"/>
            <p:treeNode>
                <h:outputText value="#{node}"/>
            </p:treeNode>
        </p:tree>

    </ui:define>
</ui:composition>

src/main/webapp/views/chapter6/megaMenu.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">

        <h3 style="margin-top:0">Horizontal MegaMenu</h3>
        
        <ui:include src="/views/chapter6/megaMenuStructure.xhtml">
            <ui:param name="orientation" value="horizontal"/>
        </ui:include>
        
        <h3 style="margin-top: 20px;">Vertical MegaMenu</h3>
        
        <ui:include src="/views/chapter6/tieredMenuStructure.xhtml"/>
        
        <ui:include src="/views/chapter6/megaMenuStructure.xhtml">
            <ui:param name="orientation" value="vertical"/>
        </ui:include>
        
        <p:dialog id="shoppingCart" header="Shopping Cart"
                  widgetVar="wdgtShoppingCart">
            <h:panelGroup id="shoppingCartGrp" layout="block"
                          style="padding:20px;">
                <h:outputText value="#{megaMenuBean.items}"/>
            </h:panelGroup>
            <p:commandButton value="Close" type="button"
                             onclick="PF('wdgtShoppingCart').hide();"/>
        </p:dialog>

    </ui:define>
</ui:composition>

src/main/webapp/views/chapter6/megaMenuStructure.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:p="http://primefaces.org/ui">

    <p:megaMenu orientation="#{orientation}">
        <p:submenu label="Women's Clothing" icon="ui-icon-person">
            <p:column>
                <p:submenu label="Shoes">
                    <p:menuitem value="Size UK 3-5" url="#"/>
                    <p:menuitem value="Size UK 6-8" url="#"/>
                </p:submenu>
                <p:submenu label="Jeans">
                    <p:menuitem value="Curve" url="#"/>
                    <p:menuitem value="Maternity" url="#"/>
                    <p:menuitem value="Petites" url="#"/>
                </p:submenu>
                <p:submenu label="Nightwear">
                    <p:menuitem value="Calvin Klein" url="#"/>
                    <p:menuitem value="Curvy Kate" url="#"/>
                </p:submenu>
            </p:column>
            <p:column>
                <p:submenu label="Leggings">
                    <p:menuitem value="Long Sleeve" url="#"/>
                    <p:menuitem value="Short Sleeve" url="#"/>
                </p:submenu>
                <p:submenu label="Skirts">
                    <p:menuitem value="American Apparel" url="#"/>
                    <p:menuitem value="American Vintage" url="#"/>
                    <p:menuitem value="Aqua" url="#"/>
                    <p:menuitem value="Dagmar" url="#"/>
                    <p:menuitem value="Osasis" url="#"/>
                </p:submenu>
            </p:column>
        </p:submenu>
    
        <p:submenu label="Men's Clothing" icon="ui-icon-person">
            <p:column>
                <p:submenu label="Shoes">
                    <p:menuitem value="Size UK 3-5" url="#"/>
                    <p:menuitem value="Size UK 6-8" url="#"/>
                    <p:menuitem value="Size UK 9-12" url="#"/>
                </p:submenu>
                <p:submenu label="T-Shirts">
                    <p:menuitem value="Addict" url="#"/>
                    <p:menuitem value="Diesel" url="#"/>
                    <p:menuitem value="Edwin" url="#"/>
                    <p:menuitem value="Sol Angeles" url="#"/>
                    <p:menuitem value="Ted Baker" url="#"/>
                    <p:menuitem value="The Only Son" url="#"/>
                </p:submenu>
            </p:column>
            <p:column>
                <p:submenu label="Leather Jackets">
                    <p:menuitem value="Diesel" url="#"/>
                    <p:menuitem value="Superdry" url="#"/>
                </p:submenu>
                <p:submenu label="Jeans">
                    <p:menuitem value="Curve" url="#"/>
                    <p:menuitem value="Maternity" url="#"/>
                    <p:menuitem value="Petites" url="#"/>
                </p:submenu>
                <p:submenu label="Swimwear">
                    <p:menuitem value="Boss Black" url="#"/>
                    <p:menuitem value="Fred Perry" url="#"/>
                    <p:menuitem value="G-Star" url="#"/>
                    <p:menuitem value="Humor" url="#"/>
                </p:submenu>
            </p:column>
        </p:submenu>
    
        <p:submenu label="Color Guide" icon="ui-icon-image">
            <p:column>
                <h:graphicImage library="images" name="colors.gif"/>
            </p:column>
        </p:submenu>
    
        <p:menuitem value="Shopping Cart"
                    onclick="PF('wdgtShoppingCart').show();"
                    update="shoppingCartGrp" icon="ui-icon-cart"/>
    </p:megaMenu>

</ui:composition>

src/main/webapp/views/chapter6/programmaticMenu.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">

        <h3 style="margin-top:0">Programmatic menu</h3>

        <p:growl id="growl"/>

        <p:menu model="#{programmaticMenuBean.model}"/>
        
        <p:menu model="#{parametrizedCommandBean.model}"
                style="width: 200px; margin-top: 20px;"/>

    </ui:define>
</ui:composition>