src/main/java/org/primefaces/cookbook/controller/chapter9/ChartBean.java
package org.primefaces.cookbook.controller.chapter9;

import org.primefaces.cookbook.utils.MessageUtil;
import org.primefaces.event.ItemSelectEvent;
import org.primefaces.model.chart.*;

import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import java.io.Serializable;

/**
 * User: mertcaliskan
 * Date: 9/18/12
 */
@Named
@ViewScoped
public class ChartBean implements Serializable {

    private LineChartModel lineModel;
    private LineChartModel areaModel;
    private BarChartModel barModel;
    private PieChartModel pieModel;
    private PieChartModel liveChartModel;
    private CartesianChartModel combinedModel;

    @PostConstruct
    public void setup() {
        lineModel = createLineModel();
        areaModel = createAreaModel();
        barModel = createBarModel();
        pieModel = createPieChartModel();
        liveChartModel = new PieChartModel();
        combinedModel = new BarChartModel();
    }

    private LineChartModel createLineModel() {
        LineChartModel model = new LineChartModel();
        LineChartSeries sales = new LineChartSeries();
        sales.setLabel("Sales");
        sales.set(2004, 1000);
        sales.set(2005, 1170);
        sales.set(2006, 660);
        sales.set(2007, 1030);

        LineChartSeries expenses = new LineChartSeries();
        expenses.setLabel("Expenses");
        expenses.set(2004, 400);
        expenses.set(2005, 460);
        expenses.set(2006, 1120);
        expenses.set(2007, 540);

        model.addSeries(sales);
        model.addSeries(expenses);
        model.setExtender("chart");
        model.setTitle("Company Performance");

        return model;
    }

    private LineChartModel createAreaModel() {
        LineChartModel model = new LineChartModel();
        LineChartSeries sales = new LineChartSeries();
        sales.setFill(true);
        sales.setLabel("Sales");
        sales.set(2004, 1000);
        sales.set(2005, 1170);
        sales.set(2006, 660);
        sales.set(2007, 1030);

        LineChartSeries expenses = new LineChartSeries();
        expenses.setFill(true);
        expenses.setLabel("Expenses");
        expenses.set(2004, 400);
        expenses.set(2005, 460);
        expenses.set(2006, 1120);
        expenses.set(2007, 540);

        model.addSeries(sales);
        model.addSeries(expenses);
        model.setExtender("chart");
        model.setTitle("Company Performance");

        return model;
    }

    private BarChartModel createBarModel() {
        BarChartModel model = new BarChartModel();
        ChartSeries sales = new ChartSeries();
        sales.setLabel("Sales");
        sales.set(2004, 1000);
        sales.set(2005, 1170);
        sales.set(2006, 660);
        sales.set(2007, 1030);

        ChartSeries expenses = new ChartSeries();
        expenses.setLabel("Expenses");
        expenses.set("2004", 400);
        expenses.set("2005", 460);
        expenses.set("2006", 1120);
        expenses.set("2007", 540);

        model.addSeries(sales);
        model.addSeries(expenses);
        model.setTitle("Company Performance");

        return model;
    }

    private PieChartModel createPieChartModel() {
        PieChartModel model = new PieChartModel();
        model.setLegendPosition("w");
        model.setShowDataLabels(true);
        model.set("Work", 11);
        model.set("Eat", 2);
        model.set("Commute", 2);
        model.set("Watch TV", 2);
        model.set("Sleep", 7);

        return model;
    }

    public PieChartModel getLivePieModel() {
        int random1 = (int)(Math.random() * 1000);
        int random2 = (int)(Math.random() * 1000);

        liveChartModel.getData().put("Candidate 1", random1);
        liveChartModel.getData().put("Candidate 2", random2);
        liveChartModel.setLegendPosition("w");
        liveChartModel.setShowDataLabels(true);

        return liveChartModel;
    }

    public CartesianChartModel getCombinedModel() {
        LineChartSeries sales = new LineChartSeries();
        sales.setLabel("Sales");
        sales.set(2004, 1000);
        sales.set(2005, 1170);
        sales.set(2006, 660);
        sales.set(2007, 1030);

        BarChartSeries expenses = new BarChartSeries();
        expenses.setLabel("Expenses");
        expenses.set("2004", 400);
        expenses.set("2005", 460);
        expenses.set("2006", 1120);
        expenses.set("2007", 540);

        combinedModel.addSeries(sales);
        combinedModel.addSeries(expenses);

        return combinedModel;
    }

    public void itemSelect(ItemSelectEvent event) {
        MessageUtil.addInfoMessageWithoutKey("Item selected",
                "Item Index:" + event.getItemIndex() + ", Series Index: " + event.getSeriesIndex());
    }

    public LineChartModel getAreaModel() {
        return areaModel;
    }

    public LineChartModel getLineModel() {
        return lineModel;
    }

    public BarChartModel getBarModel() {
        return barModel;
    }

    public PieChartModel getPieModel() {
        return pieModel;
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter9/MapBean.java
package org.primefaces.cookbook.controller.chapter9;

import org.primefaces.cookbook.utils.MessageUtil;
import org.primefaces.event.map.MarkerDragEvent;
import org.primefaces.event.map.OverlaySelectEvent;
import org.primefaces.model.map.*;

import javax.faces.view.ViewScoped;
import javax.inject.Named;
import java.io.Serializable;

/**
 * User: mertcaliskan
 * Date: 10/10/12
 */
@Named
@ViewScoped
public class MapBean implements Serializable {
                           
    private MapModel markerModel = new DefaultMapModel();
    private MapModel draggableMarkerModel = new DefaultMapModel();
    private MapModel polylineModel = new DefaultMapModel();
    private MapModel polygonModel = new DefaultMapModel();
    private MapModel circleModel = new DefaultMapModel();
    private MapModel rectangleModel = new DefaultMapModel();

    private Marker selectedMarker;

    public MapBean() {
        markerModel.addOverlay(new Marker(new LatLng(41.073399, 29.051971), "Bosphorus", "bosphorus.jpg"));
        markerModel.addOverlay(new Marker(new LatLng(41.118418, 29.134026), "Bosphorus", "bosphorus.jpg"));

        Marker marker1 = new Marker(new LatLng(41.073399, 29.051971), "Bosphorus", "bosphorus.jpg");
        marker1.setDraggable(true);
        draggableMarkerModel.addOverlay(marker1);
        Marker marker2 = new Marker(new LatLng(41.118418, 29.134026), "Bosphorus", "bosphorus.jpg");
        marker2.setDraggable(true);
        draggableMarkerModel.addOverlay(marker2);

        Polyline polyline = new Polyline();
        polyline.getPaths().add(new LatLng(41.073399, 29.051971));
        polyline.getPaths().add(new LatLng(41.118418, 29.134026));
        polyline.getPaths().add(new LatLng(41.027807, 29.049973));
        polylineModel.addOverlay(polyline);

        Polygon polygon = new Polygon();
        polygon.getPaths().add(new LatLng(41.073399, 29.051971));
        polygon.getPaths().add(new LatLng(41.118418, 29.134026));
        polygon.getPaths().add(new LatLng(41.027807, 29.049973));
        polygonModel.addOverlay(polygon);

        Circle circle = new Circle(new LatLng(41.073399, 29.051971), 5000);
        circleModel.addOverlay(circle);

        rectangleModel.addOverlay(new Rectangle(new LatLngBounds(new LatLng(41.073399, 29.051971), new LatLng(41.118418, 29.134026))));

    }

    public void onMarkerSelect(OverlaySelectEvent event) {
        Marker selectedMarker = (Marker) event.getOverlay();
        MessageUtil.addInfoMessageWithoutKey(selectedMarker.getTitle(), selectedMarker.getLatlng().toString());
    }

    public void onMarkerDrag(MarkerDragEvent event) {
        MessageUtil.addInfoMessage("marker.dragged", event.getMarker().getLatlng().toString());
    }


    public void selectMarker(OverlaySelectEvent event) {
        selectedMarker = (Marker) event.getOverlay();
    }

    public MapModel getMarkerModel() {
        return markerModel;
    }

    public MapModel getDraggableMarkerModel() {
        return draggableMarkerModel;
    }

    public MapModel getPolylineModel() {
        return polylineModel;
    }

    public MapModel getPolygonModel() {
        return polygonModel;
    }

    public MapModel getCircleModel() {
        return circleModel;
    }

    public MapModel getRectangleModel() {
        return rectangleModel;
    }

    public Marker getSelectedMarker() {
        return selectedMarker;
    }
}

src/main/webapp/views/chapter9/chart.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/masterLayout.xhtml">
    <ui:define name="head">
        <script type="text/javascript">
        function chart() {
            this.cfg.axes.xaxis.tickOptions = {
                formatString : '%d'
            };
        }
        </script>
    </ui:define>
    <ui:define name="chapterItem">
        <h3 style="margin-top:0">Charting with Line</h3>
        <p:growl id="growl" showDetail="true"/>
        <h:panelGrid columns="2" cellpadding="5">

            <h:outputText value="Line Chart" />
            <p:chart type="line" model="#{chartBean.lineModel}" style="height:250px" />

            <h:outputText value="Area Chart" />
            <p:chart type="line" model="#{chartBean.areaModel}" style="height:250px" />

            <h:outputText value="Bar Chart" />
            <p:chart type="bar" model="#{chartBean.barModel}" style="height:250px" />

            <h:outputText value="Pie Chart" />
            <p:chart type="pie" model="#{chartBean.pieModel}" style="height:250px" />
        </h:panelGrid>
    </ui:define>
</ui:composition>

src/main/webapp/views/chapter9/chartInteraction.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">
        <h3 style="margin-top:0">Interacting with charts via AJAX</h3>
        <p:growl id="growl" showDetail="true" />
        <h:panelGrid columns="2" cellpadding="5">

            <h:outputText value="With AJAX Behavior Event" />
            <p:chart type="bar" id="withAjax" model="#{chartBean.barModel}" style="height:250px">
                <p:ajax event="itemSelect" listener="#{chartBean.itemSelect}" update="growl" />
            </p:chart>

        </h:panelGrid>
    </ui:define>
</ui:composition>

src/main/webapp/views/chapter9/combinedChart.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">
        <h3 style="margin-top:0">Interacting with charts via AJAX</h3>
        <p:growl id="growl" showDetail="true" />
        <h:panelGrid columns="2" cellpadding="5">

            <h:outputText value="Line and Bar Chart combined" />
            <p:chart type="bar" id="combined" model="#{chartBean.combinedModel}" style="height:250px" />

        </h:panelGrid>
    </ui:define>
</ui:composition>

src/main/webapp/views/chapter9/map.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/masterLayout.xhtml">

    <ui:define name="head">
        <script src="http://maps.google.com/maps/api/js?sensor=true" type="text/javascript"></script>
    </ui:define>

    <ui:define name="chapterItem">
        <h3 style="margin-top:0">Basic Mapping with GMaps</h3>
        <p:growl id="growl" showDetail="true"/>

        <h:panelGrid columns="2" cellpadding="5">

            <h:outputText value="Simple" />
            <p:gmap center="41.106261, 29.057465" zoom="10" type="hybrid" style="width:600px;height:400px" />

            <h:outputText value="Without Controls" />
            <p:gmap center="41.106261, 29.057465" zoom="10" type="roadmap" style="width:600px;height:400px"
                    model="#{mapBean.markerModel}" disableDefaultUI="true" />

        </h:panelGrid>
    </ui:define>
</ui:composition>

src/main/webapp/views/chapter9/mapDrawings.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/masterLayout.xhtml">

    <ui:define name="head">
        <script src="http://maps.google.com/maps/api/js?sensor=true" type="text/javascript"></script>
    </ui:define>

    <ui:define name="chapterItem">
        <h3 style="margin-top:0">Creating Rectangles, Circles, Polylines and Polygons in Maps</h3>
        <p:growl id="growl" showDetail="true"/>

        <h:panelGrid columns="2" cellpadding="5">

            <h:outputText value="With Rectangle" />
            <p:gmap center="41.106261, 29.057465" zoom="10" type="roadmap" style="width:600px;height:400px"
                    model="#{mapBean.rectangleModel}" />

            <h:outputText value="With Circle" />
            <p:gmap center="41.106261, 29.057465" zoom="10" type="roadmap" style="width:600px;height:400px"
                    model="#{mapBean.circleModel}" />

            <h:outputText value="With Polylines" />
            <p:gmap center="41.106261, 29.057465" zoom="11" type="roadmap" style="width:600px;height:400px"
                    model="#{mapBean.polylineModel}" />

            <h:outputText value="With Polygons" />
            <p:gmap center="41.106261, 29.057465" zoom="11" type="roadmap" style="width:600px;height:400px"
                    model="#{mapBean.polygonModel}" />

        </h:panelGrid>
    </ui:define>
</ui:composition>

src/main/webapp/views/chapter9/mapInfoView.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/masterLayout.xhtml">

    <ui:define name="head">
        <script src="http://maps.google.com/maps/api/js?sensor=true" type="text/javascript"></script>
    </ui:define>

    <ui:define name="chapterItem">
        <h3 style="margin-top:0">Adding, Selecting and Dragging Markers in Maps</h3>
        <p:growl id="growl" showDetail="true"/>

        <h:panelGrid columns="2" cellpadding="5">
            <h:outputText value="With Information Window" />
            <p:gmap id="withInformation" center="41.106261, 29.057465" zoom="10" type="roadmap" style="width:600px;height:400px" model="#{mapBean.markerModel}">
                <p:ajax event="overlaySelect" listener="#{mapBean.selectMarker}" />
                <p:gmapInfoWindow id="infoWindow">
                    <p:graphicImage value="/resources/images/map/#{mapBean.selectedMarker.data}" />
                </p:gmapInfoWindow>
            </p:gmap>

            <h:outputText value="With Street View" />
            <p:gmap center="40.759011,-73.984472" type="roadmap" zoom="15" style="width:600px;height:400px" streetView="true" />
        </h:panelGrid>
    </ui:define>
</ui:composition>

src/main/webapp/views/chapter9/mapMarkers.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/masterLayout.xhtml">

    <ui:define name="head">
        <script src="http://maps.google.com/maps/api/js?sensor=true" type="text/javascript"></script>
    </ui:define>

    <ui:define name="chapterItem">
        <h3 style="margin-top:0">Adding, Selecting and Dragging Markers in Maps</h3>
        <p:growl id="growl" showDetail="true"/>

        <h:panelGrid columns="2" cellpadding="5">

            <h:outputText value="With Markers" />
            <p:gmap center="41.106261, 29.057465" zoom="10" type="roadmap" style="width:600px;height:400px"
                    model="#{mapBean.markerModel}" />

            <h:outputText value="With Selection" />
            <p:gmap center="41.106261, 29.057465" zoom="10" type="roadmap" style="width:600px;height:400px"
                    model="#{mapBean.markerModel}" >
                <p:ajax event="overlaySelect" listener="#{mapBean.onMarkerSelect}" update="growl" />
            </p:gmap>

            <h:outputText value="With Drag and Drop" />
            <p:gmap center="41.106261, 29.057465" zoom="10" type="roadmap" style="width:600px;height:400px"
                    model="#{mapBean.draggableMarkerModel}" >
                <p:ajax event="markerDrag" listener="#{mapBean.onMarkerDrag}" update="growl" />
            </p:gmap>
        </h:panelGrid>
    </ui:define>
</ui:composition>

src/main/webapp/views/chapter9/pollingChart.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">
        <h3 style="margin-top:0">Updating live data in charts with polling</h3>
        <p:growl id="growl" showDetail="true"/>

        <h:panelGrid columns="3" cellpadding="5">

            <h:outputText value="Live Update" />
            <p:poll interval="2" update="live" />
            <p:chart id="live" type="pie" model="#{chartBean.livePieModel}" style="height:250px" />

        </h:panelGrid>

    </ui:define>
</ui:composition>