src/main/java/org/primefaces/cookbook/model/chapter3/Car.java
package org.primefaces.cookbook.model.chapter3;

import java.io.Serializable;

/**
 * User: mertcaliskan
 * Date: 7/9/12
 */
public class Car implements Serializable {

    public String name;
    public int year;

    public Car(String name, int year) {
        this.name = name;
        this.year = year;
    }

    public String getName() {
        return name;
    }

    public int getYear() {
        return year;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setYear(int year) {
        this.year = year;
    }

    @Override
    public String toString() {
        return getName();
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter3/AutoCompleteBean.java
package org.primefaces.cookbook.controller.chapter3;

import org.apache.commons.lang3.RandomStringUtils;
import org.primefaces.cookbook.converter.CarConverter;
import org.primefaces.cookbook.model.chapter3.Car;
import org.primefaces.cookbook.utils.MessageUtil;
import org.primefaces.event.SelectEvent;

import javax.faces.view.ViewScoped;
import javax.inject.Named;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.Set;

/**
 * User: mertcaliskan
 * Date: 6/11/12
 */
@Named
@ViewScoped
public class AutoCompleteBean implements Serializable {

    private String txt1;
    private String txt2;
    private String txt3;
    private String txt4;
    private String txt5;
    private String txt6;
    private String txt7;
    private String txt8;
    private Car selectedCar;
    private Car selectedCar2;
    private List<String> selectedTexts;

    public String getTxt1() {
        return txt1;
    }

    public void setTxt1(String txt1) {
        this.txt1 = txt1;
    }

    public String getTxt2() {
        return txt2;
    }

    public void setTxt2(String txt2) {
        this.txt2 = txt2;
    }

    public String getTxt3() {
        return txt3;
    }

    public void setTxt3(String txt3) {
        this.txt3 = txt3;
    }

    public String getTxt4() {
        return txt4;
    }

    public void setTxt4(String txt4) {
        this.txt4 = txt4;
    }

    public String getTxt5() {
        return txt5;
    }

    public void setTxt5(String txt5) {
        this.txt5 = txt5;
    }

    public String getTxt6() {
        return txt6;
    }

    public void setTxt6(String txt6) {
        this.txt6 = txt6;
    }

    public String getTxt7() {
        return txt7;
    }

    public void setTxt7(String txt7) {
        this.txt7 = txt7;
    }

    public String getTxt8() {
        return txt8;
    }

    public void setTxt8(String txt8) {
        this.txt8 = txt8;
    }

    public Car getSelectedCar() {
        return selectedCar;
    }

    public void setSelectedCar(Car selectedCar) {
        this.selectedCar = selectedCar;
    }

    public Car getSelectedCar2() {
        return selectedCar2;
    }

    public void setSelectedCar2(Car selectedCar2) {
        this.selectedCar2 = selectedCar2;
    }

    public List<String> getSelectedTexts() {
        return selectedTexts;
    }

    public void setSelectedTexts(List<String> selectedTexts) {
        this.selectedTexts = selectedTexts;
    }

    public List<Car> completeCar(String input) {
        List<Car> suggestions = new ArrayList<Car>();
        Set<String> keys = CarConverter.cars.keySet();

        for (String key : keys) {
            if (key.startsWith(input)) {
                suggestions.add(CarConverter.cars.get(key));
            }
        }
        return suggestions;
    }

    public List<Car> completeCarContains(String input) {
        List<Car> suggestions = new ArrayList<Car>();
        Set<String> keys = CarConverter.cars.keySet();

        for (String key : keys) {
            if (key.contains(input)) {
                suggestions.add(CarConverter.cars.get(key));
            }
        }
        return suggestions;
    }

    public void handleSelect(SelectEvent event) {
        Object selectedObject = event.getObject();
        MessageUtil.addInfoMessage("selected.object", selectedObject);
    }

    public List<String> complete(String input) {
        List<String> result = new ArrayList<String>();

        for (int i = 0; i < 10; i++) {
            result.add(input + i);
        }

        return result;
    }

    public List<String> completeNoFound(String input) {
        return null;
    }

    public char getGroup(Car car) {
        return car.getName().charAt(0);
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter3/CalendarBean.java
package org.primefaces.cookbook.controller.chapter3;

import org.apache.commons.lang3.time.DateUtils;
import org.primefaces.cookbook.utils.MessageUtil;
import org.primefaces.event.SelectEvent;

import javax.faces.view.ViewScoped;
import javax.inject.Named;
import java.io.Serializable;
import java.util.Date;

/**
 * User: mertcaliskan
 * Date: 6/28/12
 */
@Named
@ViewScoped
public class CalendarBean implements Serializable {

    private Date date;

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }
    
    public Date getYesterday() {
        return DateUtils.addDays(new Date(), -1);
    }

    public Date getTomorrow() {
        return DateUtils.addDays(new Date(), 1);
    }

    public void onDateSelect(SelectEvent event) {
        Date date = (Date)event.getObject();
        MessageUtil.addInfoMessage("selected.date", date);
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter3/EditorBean.java
package org.primefaces.cookbook.controller.chapter3;

import javax.faces.view.ViewScoped;
import javax.inject.Named;
import java.io.Serializable;

/**
 * User: mertcaliskan
 * Date: 6/30/12
 */
@Named
@ViewScoped
public class EditorBean implements Serializable {
    
    private String text;

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter3/InplaceBean.java
package org.primefaces.cookbook.controller.chapter3;

import org.primefaces.component.layout.LayoutUnit;
import org.primefaces.cookbook.utils.MessageUtil;
import org.primefaces.event.SelectEvent;

import javax.faces.event.AjaxBehaviorEvent;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import java.io.Serializable;

/**
 * Created by mertcaliskan
 * on 03/01/15.
 */
@Named
@ViewScoped
public class InplaceBean implements Serializable {
    private boolean value;

    public boolean isValue() {
        return value;
    }

    public void setValue(boolean value) {
        this.value = value;
    }

    public void handleSave(AjaxBehaviorEvent event) {
        MessageUtil.addInfoMessageWithoutKey("Input Saved!", null);
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter3/InputMaskBean.java
package org.primefaces.cookbook.controller.chapter3;

import javax.faces.view.ViewScoped;
import javax.inject.Named;
import java.io.Serializable;

/**
 * User: mertcaliskan
 * Date: 6/11/12
 */
@Named
@ViewScoped
public class InputMaskBean implements Serializable {

    private String phone;
    private String phone2;
    private String phoneExt;
    private String productKey;

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getPhone2() {
        return phone2;
    }

    public void setPhone2(String phone2) {
        this.phone2 = phone2;
    }

    public String getPhoneExt() {
        return phoneExt;
    }

    public void setPhoneExt(String phoneExt) {
        this.phoneExt = phoneExt;
    }

    public String getProductKey() {
        return productKey;
    }

    public void setProductKey(String productKey) {
        this.productKey = productKey;
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter3/InputTextAreaBean.java
package org.primefaces.cookbook.controller.chapter3;

import javax.faces.view.ViewScoped;
import javax.inject.Named;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * User: mertcaliskan
 * Date: 6/25/12
 */
@Named
@ViewScoped
public class InputTextAreaBean implements Serializable {
    
    private String value;

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public List<String> complete(String query) {
        List<String> results = new ArrayList<String>();

        if(query.equals("PrimeFaces")) {
            results.add("PrimeFaces Rocks!!!");
            results.add("PrimeFaces has 100+ components.");
            results.add("PrimeFaces is lightweight.");
            results.add("PrimeFaces Cookbook is the best source for PrimeFaces!");
        }
        else {
            for(int i = 0; i < 10; i++) {
                results.add(query + i);
            }
        }

        return results;
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter3/PasswordBean.java
package org.primefaces.cookbook.controller.chapter3;

import javax.faces.view.ViewScoped;
import javax.inject.Named;
import java.io.Serializable;

/**
 * User: mertcaliskan
 * Date: 7/19/12
 */
@Named
@ViewScoped
public class PasswordBean implements Serializable {
    
    private String password;

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter3/RatingBean.java
package org.primefaces.cookbook.controller.chapter3;

import org.primefaces.cookbook.utils.MessageUtil;
import org.primefaces.event.RateEvent;

import javax.faces.view.ViewScoped;
import javax.inject.Named;
import java.io.Serializable;

/**
 * User: mertcaliskan
 * Date: 7/23/12
 */
@Named
@ViewScoped
public class RatingBean implements Serializable {

    private Integer rate;

    public Integer getRate() {
        return rate;
    }

    public void setRate(Integer rate) {
        this.rate = rate;
    }

        public void handleRate(RateEvent rateEvent) {
        Integer rate = (Integer) rateEvent.getRating();
        MessageUtil.addInfoMessage("rating.selected", rate);
    }

    public void cancelRate() {
        MessageUtil.addInfoMessage("rating.cancelled");
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter3/SelectCheckboxBean.java
package org.primefaces.cookbook.controller.chapter3;

import org.primefaces.cookbook.utils.MessageUtil;

import javax.faces.view.ViewScoped;
import javax.inject.Named;
import java.io.Serializable;
import java.util.List;

/**
 * User: mertcaliskan
 * Date: 6/26/12
 */
@Named
@ViewScoped
public class SelectCheckboxBean implements Serializable {

    private boolean selectedValue;

    private List<String> selectedCountries;

    public boolean isSelectedValue() {
        return selectedValue;
    }

    public void setSelectedValue(boolean selectedValue) {
        this.selectedValue = selectedValue;
    }

    public List<String> getSelectedCountries() {
        return selectedCountries;
    }

    public void setSelectedCountries(List<String> selectedCountries) {
        this.selectedCountries = selectedCountries;
    }

    public void addMessage() {
        String summaryKey = selectedValue ? "checkbox.checked" : "checkbox.unchecked";

        MessageUtil.addInfoMessage(summaryKey);
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter3/SelectOneMenuBean.java
package org.primefaces.cookbook.controller.chapter3;

import org.primefaces.cookbook.converter.CarConverter;
import org.primefaces.cookbook.model.chapter3.Car;

import javax.annotation.PostConstruct;
import javax.faces.bean.ViewScoped;
import javax.inject.Named;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * Created by mertcaliskan
 * on 04/01/15.
 */
@Named
@ViewScoped
public class SelectOneMenuBean implements Serializable {

    private List<Car> cars;
    private Car selectedCar;

    @PostConstruct
    public void setup() {
        cars = new ArrayList<Car>(CarConverter.cars.values());
    }

    public char getGroup(Car car) {
        return car.getName().charAt(0);
    }

    public List<Car> getCars() {
        return cars;
    }

    public void setCars(List<Car> cars) {
        this.cars = cars;
    }

    public Car getSelectedCar() {
        return selectedCar;
    }

    public void setSelectedCar(Car selectedCar) {
        this.selectedCar = selectedCar;
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter3/SliderBean.java
package org.primefaces.cookbook.controller.chapter3;

import org.primefaces.cookbook.utils.MessageUtil;
import org.primefaces.event.SlideEndEvent;

import javax.faces.view.ViewScoped;
import javax.inject.Named;
import java.io.Serializable;

/**
 * User: mertcaliskan
 * Date: 7/1/12
 */
@Named
@ViewScoped
public class SliderBean implements Serializable {

    private int intValue = 0;
    private int rangeStart = 20;
    private int rangeEnd = 60;

    public int getIntValue() {
        return intValue;
    }

    public void setIntValue(int intValue) {
        this.intValue = intValue;
    }

    public int getRangeStart() {
        return rangeStart;
    }

    public void setRangeStart(int rangeStart) {
        this.rangeStart = rangeStart;
    }

    public int getRangeEnd() {
        return rangeEnd;
    }

    public void setRangeEnd(int rangeEnd) {
        this.rangeEnd = rangeEnd;
    }

    public void onSlideEnd(SlideEndEvent event) {
        int value = event.getValue();
        MessageUtil.addInfoMessage("selected.sliderValue", value);
    }
}

src/main/java/org/primefaces/cookbook/controller/chapter3/SpinnerBean.java
package org.primefaces.cookbook.controller.chapter3;

import javax.faces.view.ViewScoped;
import javax.inject.Named;
import java.io.Serializable;

/**
 * User: mertcaliskan
 * Date: 7/1/12
 */
@Named
@ViewScoped
public class SpinnerBean implements Serializable {

    private int intValue = 0;
    private int intValue2 = 0;
    private double doubleValue = 0.0;

    public int getIntValue() {
        return intValue;
    }

    public void setIntValue(int intValue) {
        this.intValue = intValue;
    }

    public int getIntValue2() {
        return intValue2;
    }

    public void setIntValue2(int intValue2) {
        this.intValue2 = intValue2;
    }

    public double getDoubleValue() {
        return doubleValue;
    }

    public void setDoubleValue(double doubleValue) {
        this.doubleValue = doubleValue;
    }
}

src/main/webapp/views/chapter3/autoComplete.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">
        <h3 style="margin-top:0">Auto Suggestion with AutoComplete</h3>
        <p:growl id="growl"/>
        <h:panelGrid columns="2" cellpadding="5">
            <h:outputText value="Simple" />
            <p:autoComplete id="simple" value="#{autoCompleteBean.txt1}" completeMethod="#{autoCompleteBean.complete}" />

            <h:outputText value="Min Length (3)" />
            <p:autoComplete id="minLength" value="#{autoCompleteBean.txt2}" completeMethod="#{autoCompleteBean.complete}" minQueryLength="3" />

            <h:outputText value="Delay (2 sec)" />
            <p:autoComplete id="delay" value="#{autoCompleteBean.txt3}" completeMethod="#{autoCompleteBean.complete}" queryDelay="2000" />

            <h:outputText value="Force Selection" />
            <p:autoComplete id="forceSelection" value="#{autoCompleteBean.txt4}" completeMethod="#{autoCompleteBean.complete}" forceSelection="true" />

            <h:outputText value="With Drop Down" />
            <p:autoComplete id="dropDown" value="#{autoCompleteBean.txt5}" completeMethod="#{autoCompleteBean.complete}" dropdown="true" />

            <h:outputText value="Caching" />
            <p:autoComplete id="caching" value="#{autoCompleteBean.txt6}" completeMethod="#{autoCompleteBean.complete}" cache="true" cacheTimeout="60000" />

            <h:outputText value="Empty Message" />
            <p:autoComplete id="emptyMessage" value="#{autoCompleteBean.txt7}" completeMethod="#{autoCompleteBean.completeNoFound}" emptyMessage="No item found" />

            <h:outputText value="POJO Support &lt;br/&gt; (Name cars like: Golf, Jetta, CC, Passat, Polo, Scirocco, Touareg)" escape="false" />
            <p:autoComplete id="carPOJO" value="#{autoCompleteBean.selectedCar}" completeMethod="#{autoCompleteBean.completeCar}"
                            var="car" itemLabel="#{car.name}" itemValue="#{car}" forceSelection="true">
                <f:converter converterId="org.primefaces.cookbook.converter.CarConverter" />
                <p:column>
                    <p:graphicImage value="/resources/images/autocomplete/#{car.name}.png" width="80" height="50"/>
                </p:column>
                <p:column>#{car.name}</p:column>
            </p:autoComplete>

            <h:outputText value="Instant AJAX Selection" />
            <p:autoComplete id="simpleItemSelect" value="#{autoCompleteBean.txt1}" completeMethod="#{autoCompleteBean.complete}">
                <p:ajax event="itemSelect" listener="#{autoCompleteBean.handleSelect}" update="growl" />
            </p:autoComplete>

            <h:outputText value="Multiple Selection" />
            <p:autoComplete id="multipleSelect" value="#{autoCompleteBean.selectedTexts}" completeMethod="#{autoCompleteBean.complete}" multiple="true" />


            <h:outputText value="Item Tip &lt;br/&gt; (Name cars like: Golf, Jetta, CC, Passat, Polo, Scirocco, Touareg)" escape="false" />
            <p:autoComplete id="itemTip" value="#{autoCompleteBean.selectedCar2}" completeMethod="#{autoCompleteBean.completeCar}"
                            var="car" itemLabel="#{car.name}" itemValue="#{car}">
                <f:converter converterId="org.primefaces.cookbook.converter.CarConverter" />
                <f:facet name="itemtip">
                    <h:panelGrid columns="2" cellpadding="5">
                        <p:graphicImage value="/resources/images/autocomplete/#{car.name}.png" width="80" height="50"/>
                        <h:outputText value="#{car.name} &lt;br/&gt; #{car.year}" escape="false" />
                    </h:panelGrid>
                </f:facet>
            </p:autoComplete>

            <h:outputText value="Grouping" />
            <p:autoComplete id="grouped" value="#{autoCompleteBean.selectedCar}" completeMethod="#{autoCompleteBean.completeCarContains}"
                            var="car" itemLabel="#{car.name}" itemValue="#{car}" forceSelection="true"
                            groupBy="#{autoCompleteBean.getGroup(car)}">
                <f:converter converterId="org.primefaces.cookbook.converter.CarConverter" />
                <p:column>
                    <p:graphicImage value="/resources/images/autocomplete/#{car.name}.png" width="80" height="50"/>
                </p:column>
                <p:column>#{car.name}</p:column>
            </p:autoComplete>
        </h:panelGrid>
    </ui:define>
</ui:composition>

src/main/webapp/views/chapter3/calendar.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">
        <h3 style="margin-top:0">Basic and Advanced Calendar Scenarios</h3>
        <p:growl id="growl"/>
        <h:panelGrid columns="2" cellpadding="5">
            <h:outputText value="Basic Selection" />
            <p:calendar value="#{calendarBean.date}" />

            <h:outputText value="Using only with mouse" />
            <p:calendar value="#{calendarBean.date}">
                <f:passThroughAttribute name="onkeypress" value="return false;" />
                <f:passThroughAttribute name="onpaste" value="return false;" />
            </p:calendar>

            <h:outputText value="With Inline Mode" />
            <p:calendar value="#{calendarBean.date}" mode="inline" />

            <h:outputText value="With Paging" />
            <p:calendar id="paging" value="#{calendarBean.date}" pages="3" />

            <h:outputText value="With Show on" />
            <p:calendar id="showOn" value="#{calendarBean.date}" showOn="button" />

            <h:outputText value="Date Selection with Restricted Date Range" />
            <p:calendar id="restrictedDates" value="#{calendarBean.date}" mode="inline"
                        mindate="#{calendarBean.yesterday}"
                        maxdate="#{calendarBean.tomorrow}" />

            <h:outputText value="Calendar With Manual Input Disabled" />
            <p:calendar id="readOnlyInputCalendar" value="#{calendarBean.date}" readonlyInput="true" />

            <h:outputText value="With Bounce Effect" />
            <p:calendar id="effectCalendar" value="#{calendarBean.date}" effect="bounce" effectDuration="slow" />

            <h:outputText value="AJAX update with Calendar" />
            <p:calendar id="ajaxCalendar" value="#{calendarBean.date}" mode="inline">
                <p:ajax event="dateSelect" listener="#{calendarBean.onDateSelect}" update="growl" />
            </p:calendar>

            <h:outputText value="Picking Time with Calendar" />
            <p:calendar id="timeCalendar" value="#{calendarBean.date}" pattern="dd/MM/yyyy HH:mm:ss" disabledWeekends="" />

        </h:panelGrid>
    </ui:define>
</ui:composition>

src/main/webapp/views/chapter3/editor.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">
        <h3 style="margin-top:0">Rich Text Editing with the Editor</h3>
        <h:panelGrid columdns="2" cellpadding="5">
            <h:outputText value="Default Editor" />
            <p:editor value="#{editorBean.text}" />

            <h:outputText value="Editor with Custom Controls" />
            <p:editor value="#{editorBean.text}" controls="bold italic strikethrough" />

            <h:outputText value="Clearing Contents of Editor" />
            <h:panelGroup>
                <p:editor value="#{editorBean.text}" widgetVar="editorClear" />
                <p:commandButton type="button" value="Clear" onclick="PF('editorClear').clear()" icon="ui-icon-close" />
            </h:panelGroup>

            <h:outputText value="Selecting all of the text in Editor" />
            <h:panelGroup>
                <p:editor value="#{editorBean.text}" widgetVar="editorSelect" />
                <p:commandButton type="button" value="Select" onclick="PF('editorSelect').selectAll()" />
            </h:panelGroup>

            <h:outputText value="Editor inside Dialog Box" />
            <h:panelGroup>
                <p:dialog widgetVar="editorDialog" modal="true">
                    <p:editor />
                </p:dialog>
                <p:commandButton value="Show" onclick="PF('editorDialog').show()" />
            </h:panelGroup>

        </h:panelGrid>
    </ui:define>
</ui:composition>

src/main/webapp/views/chapter3/inPlaceEditor.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">
        <h3 style="margin-top:0">Advanced Editing with in-place Editor</h3>
        <p:growl id="growl" showDetail="true"/>

        <h:panelGrid columdns="2" cellpadding="5">

            <h:outputText value="Basic in-place Editing" />
            <p:inplace>
                <h:inputText value="Edit Me!" />
            </p:inplace>
            <hr/>

            <h:outputText value="in-place Editing with Drop Down" />
            <p:inplace label="Countries">
                <h:selectOneMenu>
                    <f:selectItem itemLabel="Turkey" itemValue="Turkey" />
                    <f:selectItem itemLabel="Germany" itemValue="Germany" />
                </h:selectOneMenu>
            </p:inplace>
            <hr/>

            <h:outputText value="in-place Editing with Label" />
            <p:inplace label="My Input Field">
                <h:inputText value="Edit Me!" />
            </p:inplace>
            <hr/>

            <h:outputText value="in-place Editing with Empty Label" />
            <p:inplace emptyLabel="My Empty Input Field">
                <h:inputText value="" />
            </p:inplace>
            <hr/>

            <h:outputText value="in-place Editing with editor='true'" />
            <p:inplace editor="true">
                <h:inputText value="Edit Me!" />
            </p:inplace>
            <hr/>

            <h:outputText value="in-place Editing with slide effect" />
            <p:inplace effect="slide">
                <h:inputText value="Edit Me!" />
            </p:inplace>
            <hr/>

            <h:outputText value="in-place Editing with slow slide effect" />
            <p:inplace effect="slide" effectSpeed="slow">
                <h:inputText value="Edit Me!" />
            </p:inplace>
            <hr/>

            <h:outputText value="in-place editing with facet (Click on the icon for editing)" />
            <p:inplace editor="true">
                <f:facet name="output">
                    <p:graphicImage value="/resources/images/inplace/#{inplaceBean.value}.png" width="30" height="30" />
                 </f:facet>
                <f:facet name="input">
                    <p:selectBooleanCheckbox value="#{inplaceBean.value}" />
                    <h:outputLabel value="PrimeFaces Rocks!" />
                </f:facet>
            </p:inplace>
            <hr/>

            <h:outputText value="in-place editing with save ajax behavior" />
            <p:inplace editor="true">
                <p:ajax event="save" listener="#{inplaceBean.handleSave}" update="growl" />
                <h:inputText value="Edit Me!" />
            </p:inplace>
            <hr/>

        </h:panelGrid>
    </ui:define>
</ui:composition>

src/main/webapp/views/chapter3/password.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/masterLayout.xhtml">
    <ui:define name="chapterItem">
        <h3 style="margin-top:0">Enhanced Password Input</h3>
        <p:growl id="growl"/>
        <h:panelGrid columns="2" cellpadding="5">
            <h:outputText value="Basic Password Input" />
            <p:password value="#{passwordBean.password}" />

            <h:outputText value="Password Input with Indicator" />
            <p:password id="feedback" value="#{passwordBean.password}" feedback="true" />

            <h:outputText value="Password Input with Inline Indicator" />
            <p:password id="feedbackInline" value="#{passwordBean.password}" feedback="true" inline="true" />

            <h:outputText value="Password Input with L10n" />
            <p:password id="passwordL10n" value="#{passwordBean.password}" feedback="true"
                        promptLabel="#{msg['password.promptLabel']}"
                        weakLabel="#{msg['password.weakLabel']}"
                        goodLabel="#{msg['password.goodLabel']}"
                        strongLabel="#{msg['password.strongLabel']}"/>

            <h:outputText value="Password Input with Match Mode" />
            <h:panelGrid id="passwords" columns="1">
                <p:messages id="messages" showDetail="true" />
                <p:password id="passwordMatch1" value="#{passwordBean.password}" match="passwordMatch2" />
                <p:password id="passwordMatch2" value="#{passwordBean.password}" />
                <p:commandButton update="passwords" value="Save" />
            </h:panelGrid>

        </h:panelGrid>
    </ui:define>
</ui:composition>